//
//  HomeWorker.swift
//  Rates Swift
//
//  Created by Artashes Noknok on 7/16/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

class HomeWorker
{
    
    var basketballAPI = NetworkAPI(baseUrl: Constants.NetworkingPaths.baseURL!)
    
    
    func getRates() -> Observable<RatesListResponse>
    {
        let ratesCommand = RateCommand(method: Constants.APIKeysAndMethods.mobyPre,
                                        uid: Constants.PostBodyConstants.uid,
                                        type: Constants.PostBodyConstants.type,
                                        rid: Constants.PostBodyConstants.rid,
                                        parameterR:  Constants.PostBodyConstants.rid,
                                        parameterD:  Constants.PostBodyConstants.uid,
                                        parameterT:  Constants.PostBodyConstants.type,
                                        parameterV:  Constants.PostBodyConstants.version)
        return basketballAPI.command(data: ratesCommand)
    }
}
